[theme]
primaryColor = "#C95232"
backgroundColor = "#E6DDC9"
secondaryBackgroundColor = "#F4EFE6"
textColor = "#141418"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
